
services:
  node-1:
    build:
      context: .   
    container_name: node_1
    ports:
      - "5001:8080"
    environment:
      - PORT=5000
    networks:
      psi-network:
        ipv4_address: 192.168.1.10
    command: ["/bin/bash", "/app/start.sh"]

  node-2:
    build:
      context: .   
    container_name: node_2
    ports:
      - "5002:8080"  
    environment:
      - PORT=5000
    networks:
      psi-network:
        ipv4_address: 192.168.1.20
    command: ["/bin/bash", "/app/start.sh"]

  node-3:
    build:
      context: .   
    container_name: node_3
    ports:
      - "5003:8080"  
    environment:
      - PORT=5000
    networks:
      psi-network:
        ipv4_address: 192.168.1.30
    command: ["/bin/bash", "/app/start.sh"]

  node-4:
    build:
      context: .  
    container_name: node_4
    ports:
      - "5004:8080"  
    environment:
      - PORT=5000
    networks:
      psi-network:
        ipv4_address: 192.168.1.40
    command: ["/bin/bash", "/app/start.sh"]


networks:
  psi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
